version: "3.3"

# O container do NGINX seria para uma versão de produção,
# no arquivo de configuração já foram configuradas as proxies
# para as calls de URL que são passadas para o back e o front.
# aqui eu vou subir o front e o back separadamente e expor
# ambas portas 8000 e 8080 do ambiente local.

volumes:
  rabbitmq_data: {}

services:
  image-resizer-api:
    build:
      context: ./image-resizer-api
    volumes:
      - ./image-resizer-api:/app
    command: /boot.sh
    ports:
      - "8000:8000"
    restart: on-failure
  image-resizer-front:
    image: node:11
    command: yarn serve
    ports:
      - "8080:8080"
    volumes:
      - ./image-resizer-front:/app
    working_dir: /app
    restart: on-failure
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data
  celery:
    build:
      context: image-resizer-api
      dockerfile: Dockerfile
    command: celery -A image worker -c 4 -l info
    volumes:
      - ./image-resizer-api:/app
    depends_on:
      - image-resizer-api
