version: "3.3"

volumes:
  rabbitmq_data: {}

services:
  back-end:
    build:
      context: ./back-end
    volumes:
      - ./back-end:/app
    command: /boot.sh
    ports:
      - "8000:8000"
    restart: on-failure
  front-end:
    image: node:8
    command: npm run start
    ports:
      - "8080:8080"
    volumes:
      - ./front-end:/app
    working_dir: /app
    restart: on-failure
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data
  celery:
    build:
      context: back-end
      dockerfile: Dockerfile
    command: celery -A image worker -c 4 -l info
    volumes:
      - ./back-end:/app
    depends_on:
      - back-end
